CREATE TABLE `autonomous_actions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`syncId` int,
	`campaignId` varchar(128),
	`campaignName` varchar(512),
	`actionType` varchar(64) NOT NULL,
	`riskLevel` enum('low','medium','high','monitor') NOT NULL,
	`status` enum('auto_executed','pending_approval','approved','rejected','undone','monitoring','expired') NOT NULL,
	`title` varchar(512) NOT NULL,
	`description` text,
	`recommendation` text,
	`actionParams` json,
	`campaignMetrics` json,
	`confidence` int,
	`impactEstimate` enum('low','medium','high'),
	`reviewedBy` varchar(256),
	`reviewedAt` timestamp,
	`isUndone` boolean DEFAULT false,
	`undoneAt` timestamp,
	`undoReason` text,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autonomous_actions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `autonomous_sync_status` (
	`id` int AUTO_INCREMENT NOT NULL,
	`platform` varchar(64) NOT NULL,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`campaignsProcessed` int DEFAULT 0,
	`actionsGenerated` int DEFAULT 0,
	`actionsAutoExecuted` int DEFAULT 0,
	`errorMessage` text,
	`metadata` json,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `autonomous_sync_status_id` PRIMARY KEY(`id`)
);
