CREATE TABLE `communication_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recipient_type` enum('member','lead') NOT NULL,
	`recipient_id` int,
	`recipient_email` varchar(255),
	`recipient_phone` varchar(20),
	`recipient_name` varchar(200),
	`channel` enum('sms','email','push') NOT NULL,
	`direction` enum('outbound','inbound') NOT NULL DEFAULT 'outbound',
	`subject` varchar(500),
	`body` text NOT NULL,
	`comm_status` enum('queued','sent','delivered','failed','bounced','opened','clicked') NOT NULL DEFAULT 'queued',
	`provider` enum('twilio_sms','twilio_email','encharge','boomerang_push') NOT NULL,
	`provider_message_id` varchar(255),
	`provider_status` varchar(100),
	`error_message` text,
	`campaign_name` varchar(255),
	`cost_cents` int,
	`sent_at` bigint,
	`delivered_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `communication_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `email_captures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(255) NOT NULL,
	`first_name` varchar(100),
	`last_name` varchar(100),
	`phone` varchar(20),
	`source` enum('web_form','meta_lead_ad','giveaway','clickfunnels','instagram','manual_csv','boomerang','acuity','referral','walk_in','other') NOT NULL DEFAULT 'other',
	`source_detail` varchar(255),
	`status` enum('new','contacted','qualified','converted','unsubscribed','bounced') NOT NULL DEFAULT 'new',
	`encharge_id` varchar(100),
	`encharge_segments` text,
	`encharge_synced_at` bigint,
	`boomerang_client_id` varchar(100),
	`boomerang_card_serial` varchar(100),
	`boomerang_synced_at` bigint,
	`converted_to_member_id` int,
	`converted_at` bigint,
	`tags` text,
	`notes` text,
	`captured_at` bigint NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `email_captures_id` PRIMARY KEY(`id`)
);
