import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Tracks the state of each autonomous data sync cycle.
 * Records when syncs started/completed, which platform was synced,
 * how many campaigns were processed, and any errors encountered.
 */
export const autonomousSyncStatus = mysqlTable("autonomous_sync_status", {
  id: int("id").autoincrement().primaryKey(),
  /** Which platform was synced: meta_ads, acuity, all */
  platform: varchar("platform", { length: 64 }).notNull(),
  /** Current status of this sync cycle */
  status: mysqlEnum("status", ["running", "completed", "failed"]).notNull().default("running"),
  /** Number of campaigns processed in this sync */
  campaignsProcessed: int("campaignsProcessed").default(0),
  /** Number of actions generated from this sync */
  actionsGenerated: int("actionsGenerated").default(0),
  /** Number of actions auto-executed */
  actionsAutoExecuted: int("actionsAutoExecuted").default(0),
  /** Error message if sync failed */
  errorMessage: text("errorMessage"),
  /** JSON blob of sync metadata (e.g., API response stats) */
  metadata: json("metadata"),
  /** When the sync started */
  startedAt: timestamp("startedAt").defaultNow().notNull(),
  /** When the sync completed (null if still running) */
  completedAt: timestamp("completedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AutonomousSyncStatus = typeof autonomousSyncStatus.$inferSelect;
export type InsertAutonomousSyncStatus = typeof autonomousSyncStatus.$inferInsert;

/**
 * Stores every autonomous action generated by the analysis engine.
 * Actions have risk levels that determine execution behavior:
 * - low: auto-executed immediately (e.g., budget decrease, pause underperformer)
 * - medium: held for approval (e.g., budget increase, targeting change)
 * - high: held for approval (e.g., email blast, campaign creation)
 * - monitor: no action taken, just tracked for observation
 */
export const autonomousActions = mysqlTable("autonomous_actions", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key to the sync that generated this action */
  syncId: int("syncId"),
  /** Meta Ads campaign ID this action relates to */
  campaignId: varchar("campaignId", { length: 128 }),
  /** Human-readable campaign name */
  campaignName: varchar("campaignName", { length: 512 }),
  /** Category of action: budget_adjustment, targeting_change, alert, pause, email, creative_refresh */
  actionType: varchar("actionType", { length: 64 }).notNull(),
  /** Risk level determines auto-execute vs approval-required */
  riskLevel: mysqlEnum("riskLevel", ["low", "medium", "high", "monitor"]).notNull(),
  /** Current status of this action */
  status: mysqlEnum("status", [
    "auto_executed",
    "pending_approval",
    "approved",
    "rejected",
    "undone",
    "monitoring",
    "expired",
  ]).notNull(),
  /** Short title describing the action */
  title: varchar("title", { length: 512 }).notNull(),
  /** Detailed description of what the action does and why */
  description: text("description"),
  /** The specific recommendation or change (e.g., "Reduce daily budget from $50 to $35") */
  recommendation: text("recommendation"),
  /** JSON blob with action-specific parameters (e.g., { oldBudget: 50, newBudget: 35 }) */
  actionParams: json("actionParams"),
  /** JSON blob with campaign metrics at time of analysis */
  campaignMetrics: json("campaignMetrics"),
  /** Confidence score from the analysis engine (0-100) */
  confidence: int("confidence"),
  /** Impact estimate: low, medium, high */
  impactEstimate: mysqlEnum("impactEstimate", ["low", "medium", "high"]),
  /** Who approved/rejected (null if auto-executed or pending) */
  reviewedBy: varchar("reviewedBy", { length: 256 }),
  /** When the action was reviewed */
  reviewedAt: timestamp("reviewedAt"),
  /** Whether this action has been undone */
  isUndone: boolean("isUndone").default(false),
  /** When the action was undone */
  undoneAt: timestamp("undoneAt"),
  /** Reason for undo */
  undoReason: text("undoReason"),
  /** Expiration time for pending actions */
  expiresAt: timestamp("expiresAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AutonomousAction = typeof autonomousActions.$inferSelect;
export type InsertAutonomousAction = typeof autonomousActions.$inferInsert;
