/**
 * Stripe Snapshot Cache
 *
 * Reads the processed Stripe subscriptions snapshot from server/stripe-snapshot.json.
 * The JSON is generated by re-running the audit CSV parse script whenever a new
 * Stripe export is received. No live Stripe API call is made here.
 *
 * To refresh: replace stripe-snapshot.json with output of the parse script.
 * To enable live Stripe API sync: see separate stripe-sync task (requires approval).
 */

import fs from "fs";
import path from "path";

// Resolve relative to project root (process.cwd() = repo root at runtime)
const SNAPSHOT_PATH = path.join(process.cwd(), "server", "stripe-snapshot.json");

export interface StripeTierRow {
  tier: string;
  count: number;
  mrr: number;
}

export interface StripeContact {
  name: string;
  email: string;
  tier: string;
  billing: string;
  monthlyCharge: number;
  mrrContribution: number;
  stripeSubId: string;
  stripeCustomerId: string;
  memberSince: string;
  multiSub: boolean;
}

export interface StripeSnapshot {
  generatedAt: string;
  exportDate: string;
  source: string;
  venueId: number;
  summary: {
    payingMembers: number;
    compedStaff: number;
    totalActive: number;
    mrr: number;
    cashMrr: number;
    recognizedMrr: number;
    arr: number;
  };
  tiers: StripeTierRow[];
  contacts: StripeContact[];
}

let _cache: StripeSnapshot | null = null;

export function readStripeSnapshot(): StripeSnapshot | null {
  try {
    if (!fs.existsSync(SNAPSHOT_PATH)) {
      console.warn("[StripeCache] stripe-snapshot.json not found — Stripe snapshot unavailable");
      return null;
    }
    if (!_cache) {
      const raw = fs.readFileSync(SNAPSHOT_PATH, "utf-8");
      _cache = JSON.parse(raw) as StripeSnapshot;
    }
    return _cache;
  } catch (err) {
    console.error("[StripeCache] Failed to read stripe-snapshot.json:", err);
    return null;
  }
}

/** Invalidate the in-process cache (call after writing a new snapshot file). */
export function invalidateStripeCache(): void {
  _cache = null;
}
